- Create debugging symbols for modules as well. - Don't start parallel builds on uni-processor systems.

diff --git a/trunk/tools/make-debug-kpkg b/trunk/tools/make-debug-kpkg
--- a/trunk/tools/make-debug-kpkg
+++ b/trunk/tools/make-debug-kpkg
@@ -41,8 +41,8 @@ apt-get -y source linux-image-$VER &&
 cd linux-*${MINOR_VER}* &&
 test -r Makefile.orig || mv -v Makefile Makefile.orig &&
 sed \
-        -e 's@^\(CFLAGS_KERNEL\s*=\)@\1 -g @' \
-        -e 's@^\(AFLAGS_KERNEL\s*=\)@\1 -gdwarf-2 @' \
+	-e 's@^\(CFLAGS_\(KERNEL\|MODULE\)\s*=\)@\1 -g @' \
+	-e 's@^\(AFLAGS_\(KERNEL\|MODULE\)\s*=\)@\1 -gdwarf-2 @' \
         Makefile.orig > Makefile
 
 
@@ -71,6 +71,10 @@ done
 # Run parallel jobs when compiling the source
 if [ -z "$CONCURRENCY_LEVEL" ]; then
        	export CONCURRENCY_LEVEL=$(( `grep  -c '^processor' /proc/cpuinfo` + 1))
+	# Don't set anything for uni-processor systems
+	if [ "$CONCURRENCY_LEVEL" = 2 ]; then
+		unset CONCURRENCY_LEVEL
+	fi
 fi
 
 # Compile source and create package
@@ -93,8 +97,8 @@ if [ -r vmlinux ]; then
 #	fi
 	#bzip2 -9 vmlinux -c > ../vmlinux-${VER}${APPEND}.bz2 &&
 	#cp -v vmlinux ../vmlinux-${VER}${APPEND} &&
-	echo -e "\nGenerating object dump for vmlinux-${VER}${APPEND}..." &&
-	objdump -W vmlinux 2>/dev/null | bzip2 -z -c --best > ../objdump-${VER}${APPEND}.bz2 &&
-	echo "Done." || echo "Error generating objdump."
+#	echo -e "\nGenerating object dump for vmlinux-${VER}${APPEND}..." &&
+#	objdump -W vmlinux 2>/dev/null | bzip2 -z -c --best > ../objdump-${VER}${APPEND}.bz2 &&
+#	echo "Done." || echo "Error generating objdump."
 fi
 
