Merge branch 'master' into local/tom_magic_numbers (Commits von chrschn)

diff --git a/branches/tom_magic_numbers/tools/mount-img b/branches/tom_magic_numbers/tools/mount-img
--- a/branches/tom_magic_numbers/tools/mount-img
+++ b/branches/tom_magic_numbers/tools/mount-img
@@ -68,7 +68,7 @@ fi
 if ! mount | grep -q $DEV; then
 	if ! $SUDO mount -o ro $DEV "$MNT"; then
 		ret=$?
-		echo "Error invoking the following command:\n mount $DEV \"$MNT\"" >&2
+		echo -e "Error invoking the following command:\n mount $DEV \"$MNT\"" >&2
 		exit $ret
 	else
 		echo "Image sucessfully mounted:"
