minor tweaks

diff --git a/tools/make-debug-kpkg b/tools/make-debug-kpkg
--- a/tools/make-debug-kpkg
+++ b/tools/make-debug-kpkg
@@ -6,17 +6,20 @@ VER=$(uname -r)
 MINOR_VER=$(echo $VER | sed 's/^\([0-9]\.[0-9]\+\(\.[0-9]\+\)*\).*$/\1/')
 APPEND_VER=${VER#$MINOR_VER}${APPEND}
 
-# How do we become root?
-if [ $(id -u) == 0 ]; then
-	SUDO=""
-else
-	SUDO="sudo"
-fi
-
 # Make sure we can execute apt-get
 if ! [ -x "$(which apt-get 2>/dev/null)" ]; then
 	echo "This does not seem to be a Debian based distribution!" >&2
 	exit 1
+fi
+
+# How do we become root?
+if [ $(id -u) == 0 ]; then
+	SUDO=""
+	ROOTCMD=""
+else
+	echo "You might be prompted for your password to install depencency packages."
+	SUDO="sudo"
+	ROOTCMD="--rootcmd $SUDO"
 fi
 
 # Resolve build dependencies, get source, and prepare Makefile
@@ -35,12 +38,13 @@ if [ -z "$CONCURRENCY_LEVEL" ]; then
 fi
 
 # Compile source and create package
-make-kpkg --us --uc --append-to-version $APPEND_VER --initrd binary-arch &&
-echo "Done." || echo "Error generating kernel packages"
+make-kpkg --us --uc $ROOTCMD --append-to-version $APPEND_VER --initrd kernel_image kernel_headers || exit 1
 
-#bzip2 -9 vmlinux -c > ../vmlinux-${VER}${APPEND}.bz2
+if [ -r vmlinux ]; then
+	#bzip2 -9 vmlinux -c > ../vmlinux-${VER}${APPEND}.bz2 &&
+	#cp -v vmlinux ../vmlinux-${VER}${APPEND} &&
+	echo -e "\nGenerating object dump for vmlinux-${VER}${APPEND}..." &&
+	objdump -W vmlinux 2>/dev/null | lzma -c -2 > ../objdump-${VER}${APPEND}.lzma &&
+	echo "Done." || echo "Error generating objdump."
+fi
 
-#cp -v vmlinux ../vmlinux-${VER}${APPEND} &&
-#echo -e "\nGenerating object dump for vmlinux-${VER}${APPEND}..." &&
-#objdump -W vmlinux 2>/dev/null | lzma -c -2 > ../objdump-${VER}${APPEND}.lzma &&
-#echo "Done." || echo "Error generating objdump."
